# Generated by Django 2.1.4 on 2019-01-09 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='0', max_length=15)),
                ('agreement', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmExpend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15)),
                ('agreement', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=30)),
                ('title', models.CharField(default='', max_length=30)),
                ('number', models.CharField(max_length=15)),
                ('agreement', models.CharField(default='', max_length=500)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendproject.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm_num', models.CharField(default='0', max_length=15)),
                ('tax_rate', models.CharField(max_length=10)),
                ('invoice_document', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30)),
                ('content', models.CharField(default='', max_length=500)),
                ('begin_time', models.DateField(default=django.utils.timezone.now)),
                ('end_time', models.DateField(default=django.utils.timezone.now)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='backendproject.Department')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receivable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=30)),
                ('title', models.CharField(default='', max_length=30)),
                ('number', models.CharField(max_length=15)),
                ('agreement', models.CharField(default='', max_length=500)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendproject.Department')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendproject.Project')),
            ],
        ),
        migrations.AddField(
            model_name='income',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendproject.Receivable'),
        ),
        migrations.AddField(
            model_name='income',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendproject.Department'),
        ),
        migrations.AddField(
            model_name='income',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendproject.Project'),
        ),
        migrations.AddField(
            model_name='expend',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendproject.Project'),
        ),
        migrations.AddField(
            model_name='confirmexpend',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendproject.Expend'),
        ),
        migrations.AddField(
            model_name='confirmexpend',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendproject.Department'),
        ),
        migrations.AddField(
            model_name='confirmexpend',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendproject.Project'),
        ),
        migrations.AddField(
            model_name='advance',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendproject.Department'),
        ),
        migrations.AddField(
            model_name='advance',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendproject.Project'),
        ),
        migrations.AddField(
            model_name='advance',
            name='receivable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendproject.Receivable'),
        ),
    ]
