# Generated by Django 2.1.4 on 2019-01-05 07:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backendproject', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='begin_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='content',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='end_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default='', max_length=30),
        ),
    ]
