# Generated by Django 2.1.4 on 2019-01-08 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendproject', '0004_auto_20190105_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='0', max_length=15)),
                ('agreement', models.CharField(default='', max_length=500)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendproject.Department')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendproject.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmExpend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15)),
                ('agreement', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Expend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=30)),
                ('title', models.CharField(default='', max_length=30)),
                ('number', models.CharField(max_length=15)),
                ('agreement', models.CharField(default='', max_length=500)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendproject.Department')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendproject.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm_num', models.CharField(default='0', max_length=15)),
                ('tax_rate', models.CharField(max_length=10)),
                ('invoice_document', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Receivable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=30)),
                ('title', models.CharField(default='', max_length=30)),
                ('number', models.CharField(max_length=15)),
                ('agreement', models.CharField(default='', max_length=500)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendproject.Department')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendproject.Project')),
            ],
        ),
        migrations.AddField(
            model_name='income',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendproject.Receivable'),
        ),
        migrations.AddField(
            model_name='income',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendproject.Department'),
        ),
        migrations.AddField(
            model_name='income',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendproject.Project'),
        ),
        migrations.AddField(
            model_name='confirmexpend',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendproject.Expend'),
        ),
        migrations.AddField(
            model_name='confirmexpend',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendproject.Department'),
        ),
        migrations.AddField(
            model_name='confirmexpend',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendproject.Project'),
        ),
        migrations.AddField(
            model_name='advance',
            name='receivable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendproject.Receivable'),
        ),
    ]
